Repository cau-likelion-org/cau-likelion-next, pull requests merged in 2023-02, with the labels that each got.

#5 Footer 디자인 변경
  public/image/Instagram.png
  public/image/Mail.png
  public/image/Notion.png
  src/components/common/footer/Footer.tsx
  src/components/common/footer/FooterButton.tsx
Labels: gildong

#6 Login & SignUp merge
  .env
  package-lock.json
  public/image/alert.png
  public/image/pngwing.com.png
  src/apis/account.ts
  src/apis/index.ts
  src/components/common/layout/LayoutLogin.tsx
  src/components/login/border/BorderSection.tsx
  src/components/login/common/Diamond.tsx
  src/components/login/common/SectionWrapper.tsx
  src/components/login/contents/ContentsSection.tsx
  src/components/login/contents/component/LeftSection.tsx
  src/components/login/contents/component/LoginButton.tsx
  src/components/login/contents/component/RightSection.tsx
  src/components/login/failed/FailedMessage.tsx
  src/pages/_document.tsx
  src/pages/google.tsx
  src/pages/login/completed.tsx
  src/pages/login/failed.tsx
  src/pages/login/index.tsx
  yarn.lock
Labels: harin, young

#4 Landing 디자인 변경
  public/image/projectPic.png
  public/image/projectPic2.png
  public/image/프로그레스바.png
  public/image/프로그레스바이동.png
  src/components/home/ScrollBar/ScrollBar.tsx
  src/components/home/common/FadeInComponent.tsx
  src/components/home/introduction/IntroduceSection.tsx
  src/components/home/introduction/component/PhotoCard.tsx
  src/components/home/plan/PlanSection.tsx
  src/components/home/plan/component/PlanBox.tsx
  src/components/home/plan/component/PlanDateItem.tsx
  src/components/home/plan/component/PlanDotItem.tsx
  src/components/home/plan/component/PlanTitleItem.tsx
  src/components/home/project/ProjectSection.tsx
  src/components/home/project/component/Project.tsx
  src/components/home/project/component/ProjectButton.tsx
  src/components/home/project/component/ProjectSlider.tsx
  src/components/home/track/TrackSection.tsx
  src/components/home/track/component/TrackButton.tsx
  src/components/home/track/component/TrackDescriptionBox.tsx
  src/components/home/video/VideoSection.tsx
  src/components/home/vision/VisionSection.tsx
  src/pages/index.tsx
  src/styles/global.css
  src/utils/constant/color.ts
Labels: gildong

#14 [REFACTOR] NavBar Button 개선
  src/components/common/header/HoverButton.tsx
  src/components/common/header/NavBar.tsx
  src/components/common/header/NavButton.tsx
Labels: young

#13 Archiving 컴포넌트 구성 및 Project 페이지 구성
  next.config.js
  package-lock.json
  public/image/searchIcon.png
  src/apis/project.ts
  src/components/archiving/Archiving.tsx
  src/components/archiving/Card.tsx
  src/components/archiving/Header.tsx
  src/components/common/layout/LayoutArchiving.tsx
  src/components/project/Header/SearchSection.tsx
  src/components/project/Header/component/SearchBar.tsx
  src/components/project/Projects/ProjectsSection.tsx
  src/pages/project/index.tsx
  src/types/request.d.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, help wanted, gildong, young

#18 Project Detail 완료
  public/image/github.png
  public/image/weblink.png
  public/image/youtube.png
  src/apis/backup/project.json
  src/apis/backup/projectDetail.json
  src/apis/project.ts
  src/apis/projectDeatil.ts
  src/components/archiving/Carousel.tsx
  src/components/project/detail/DetailMainSection.tsx
  src/components/project/detail/ProjectIntroductionSection.tsx
  src/components/project/detail/TeamIntroductionSection.tsx
  src/components/project/detail/component/TeamIntroduction/DevStacks.tsx
  src/components/project/detail/component/TeamIntroduction/LinkButton.tsx
  src/components/project/detail/component/TeamIntroduction/TeamMember.tsx
  src/pages/project/[project_id].tsx
  src/types/request.d.ts
  src/utils/constant/index.ts
Labels: enhancement, gildong

#17 [FEAT] 반응형 : 모바일 NavBar, 랜딩 애니메이션 제거, 미디어 쿼리
  src/components/archiving/Header.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/header/MobileNavBar.tsx
  src/components/common/header/MobileNavModal.tsx
  src/components/common/header/NavBar.tsx
  src/components/common/header/NavProfileCard.tsx
  src/components/common/layout/LayoutArchiving.tsx
  src/components/common/layout/LayoutAttendance.tsx
  src/components/common/layout/LayoutDefault.tsx
  src/components/common/layout/LayoutLanding.tsx
  src/components/common/layout/LayoutNoHeight.tsx
  src/components/home/ScrollBar/ScrollBar.tsx
  src/components/home/activity/ActivitySection.tsx
  src/components/home/activity/component/ActivityButton.tsx
  src/components/home/activity/component/ActivityDescriptionBox.tsx
  src/components/home/introduction/IntroduceSection.tsx
  src/components/home/introduction/component/PhotoCard.tsx
  src/components/home/plan/PlanSection.tsx
  src/components/home/plan/component/PlanBox.tsx
  src/components/home/plan/component/PlanDateItem.tsx
  src/components/home/plan/component/PlanDotItem.tsx
  src/components/home/plan/component/PlanTitleItem.tsx
  src/components/home/project/ProjectSection.tsx
  src/components/home/project/component/Project.tsx
  src/components/home/project/component/ProjectSlider.tsx
  src/components/home/track/TrackSection.tsx
  src/components/home/track/component/TrackButton.tsx
  src/components/home/track/component/TrackDescriptionBox.tsx
  src/components/home/video/VideoSection.tsx
  src/components/home/vision/VisionSection.tsx
  src/components/project/Header/component/SearchBar.tsx
  src/components/signup/component/CauMailAuthenticationBox.tsx
  src/components/signup/component/DropdownMenuBox.tsx
  src/pages/google.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/utils/constant/index.ts
  src/utils/state.ts
Labels: young

#19 [FEAT] 추억 아카이빙 모아보기 / 상세 페이지 완료
  src/apis/backup/gallery.json
  src/apis/backup/galleryDetail.json
  src/apis/gallery.ts
  src/components/archiving/Archiving.tsx
  src/components/archiving/Card.tsx
  src/components/archiving/Carousel.tsx
  src/components/gallery/GalleryDetailSection.tsx
  src/components/gallery/GalleryListSection.tsx
  src/components/project/Projects/ProjectsSection.tsx
  src/pages/gallery/[gallery_id].tsx
  src/pages/gallery/index.tsx
  src/pages/project/[project_id].tsx
  src/types/request.d.ts
Labels: young

#20 [FEAT] 마이페이지 > 출석 현황, 회원 정보 수정 모달 완료
  next.config.js
  src/apis/account.ts
  src/apis/attendance.ts
  src/components/attendance/incompleted/component/AttendanceBox.tsx
  src/components/mypage/MyAttendanceSection.tsx
  src/components/mypage/component/NameCard.tsx
  src/components/mypage/component/ProfileCard.tsx
  src/components/mypage/component/UserEditModal.tsx
  src/components/signup/SignUpFormSection.tsx
  src/components/signup/component/EmailErrorModal.tsx
  src/components/signup/component/FormSendButton.tsx
  src/pages/mypage/index.tsx
  src/types/request.d.ts
  src/utils/constant/index.ts
  src/utils/state.ts
  tsconfig.json
Labels: young

#21 Archiving/detail Carousel 스크롤 상호작용 추가
  src/components/archiving/Carousel.tsx
  src/hooks/useInterval.ts
  src/hooks/useSlider.ts
Labels: gildong

#26 Archiving 데이터 타입 변경
  src/apis/backup/gallery.json
  src/apis/backup/galleryDetail.json
  src/apis/gallery.ts
  src/apis/project.ts
  src/components/archiving/Archiving.tsx
  src/components/archiving/Card.tsx
  src/components/gallery/GalleryDetailSection.tsx
  src/components/gallery/GalleryListSection.tsx
  src/components/project/projects/ProjectsSection.tsx
  src/pages/gallery/index.tsx
  src/types/request.d.ts
Labels: gildong

#22 세션 모아보기 페이지 및 세션 모달창
  .gitignore
  package-lock.json
  package.json
  public/image/Frame 916.png
  public/image/Vector 16.png
  public/image/Vector 18.png
  public/image/세션바로가기.png
  src/apis/backup/sessionData.json
  src/apis/backup/sessionDetail.json
  src/apis/session.ts
  src/apis/sessionDetail.ts
  src/components/archiving/Card.tsx
  src/components/attendance/completed/CompletedSection.tsx
  src/components/attendance/completed/component/AttendanceChecker.tsx
  src/components/attendance/completed/component/TrackAttendance.tsx
  src/components/attendance/incompleted/InCompletedSection.tsx
  src/components/attendance/incompleted/component/InputBox.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/layout/LayoutAttendance.tsx
  src/components/common/layout/LayoutLanding.tsx
  src/components/common/layout/LayoutNoHeight.tsx
  src/components/home/common/FadeInComponent.tsx
  src/components/home/introduction/IntroduceSection.tsx
  src/components/home/introduction/component/PhotoCard.tsx
  src/components/home/plan/PlanSection.tsx
  src/components/home/project/component/Project.tsx
  src/components/home/project/component/ProjectButton.tsx
  src/components/home/scrollBar/ScrollBar.tsx
  src/components/home/track/TrackSection.tsx
  src/components/home/track/component/TrackButton.tsx
  src/components/home/track/component/TrackDescriptionBox.tsx
  src/components/home/video/VideoSection.tsx
  src/components/home/vision/VisionSection.tsx
  src/components/project/header/component/SearchBar.tsx
  src/components/session/Arrow.tsx
  src/components/session/SessionDetailSection.tsx
  src/components/session/SessionModal.tsx
  src/components/session/SessionSection.tsx
  src/components/session/Slick.tsx
  src/components/session/Track.tsx
  src/components/session/utils/scrollBlock.tsx
  src/components/signup/SignUpFormSection.tsx
  src/components/signup/component/CauMailAuthenticationBox.tsx
  src/components/signup/component/DropdownMenuBox.tsx
  src/components/signup/component/EmailErrorModal.tsx
  src/pages/google.tsx
  src/pages/index.tsx
  src/pages/session/[session_id].tsx
  src/pages/session/index.tsx
  src/types/request.d.ts
  src/utils/constant/index.ts
  yarn.lock
Labels: harin

#28 Login
  .github/workflows/deploy.yml
  next.config.js
  public/image/signup.gif
  src/apis/account.ts
  src/apis/authAxios.ts
  src/apis/signUp.ts
  src/components/common/footer/FooterButton.tsx
  src/components/common/header/HoverButton.tsx
  src/components/common/header/MobileNavModal.tsx
  src/components/common/header/NavBar.tsx
  src/components/common/header/NavProfileCard.tsx
  src/components/home/activity/ActivitySection.tsx
  src/components/home/introduction/IntroduceSection.tsx
  src/components/home/project/component/Project.tsx
  src/components/login/border/BorderSection.tsx
  src/components/mypage/component/ProfileCard.tsx
  src/components/mypage/component/UserEditModal.tsx
  src/components/signup/SignUpFormSection.tsx
  src/components/signup/component/CauMailAuthenticationBox.tsx
  src/hooks/useAuthRequest.ts
  src/pages/google.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/success.tsx
  src/types/request.d.ts
  src/utils/state.ts
Labels: gildong, harin

#31 Session 페이지
  public/image/Frame 916.png
  public/image/Vector 16.png
  public/image/Vector 18.png
  public/image/세션바로가기.png
  src/apis/backup/sessionData.json
  src/apis/backup/sessionDetail.json
  src/apis/session.ts
  src/apis/sessionDetail.ts
  src/components/session/Arrow.tsx
  src/components/session/SessionDetailSection.tsx
  src/components/session/SessionModal.tsx
  src/components/session/SessionSection.tsx
  src/components/session/Slick.tsx
  src/components/session/Track.tsx
  src/pages/session/[session_id].tsx
  src/pages/session/index.tsx
  src/types/request.d.ts
Labels: harin

#32 Landing
  src/components/home/activity/ActivitySection.tsx
  src/components/home/activity/component/ActivityButton.tsx
  src/components/home/activity/component/ActivityDescriptionBox.tsx
  src/components/home/activity/component/CircleComponent.tsx
Labels: gildong
