Repository cau-likelion-org/cau-likelion-next, pull requests merged in 2023-03, with the labels that each got.

#33 아카이빙 상세 페이지 반응형 적용
  public/image/back.png
  src/apis/backup/sessionData.json
  src/apis/session.ts
  src/components/archiving/Card.tsx
  src/components/archiving/Carousel.tsx
  src/components/archiving/Header.tsx
  src/components/gallery/GalleryDetailSection.tsx
  src/components/project/detail/DetailMainSection.tsx
  src/components/session/SessionDetailSection.tsx
  src/components/session/SessionModal.tsx
  src/components/session/SessionSection.tsx
  src/components/session/Slick.tsx
  src/components/session/Track.tsx
  src/pages/session/[session_id].tsx
  src/pages/session/index.tsx
Labels: harin

#34 [FEAT] 마이페이지 : 과제점수표 노션 API 연동 & 출결점수 API 연동
  .gitignore
  package-lock.json
  package.json
  src/apis/account.ts
  src/apis/attendance.ts
  src/apis/authAxios.ts
  src/apis/project.ts
  src/apis/projectDeatil.ts
  src/components/login/contents/component/LoginButton.tsx
  src/components/mypage/MyAttendanceSection.tsx
  src/components/mypage/MyScoreSection.tsx
  src/components/mypage/TotalScoreSection.tsx
  src/components/mypage/component/NameCard.tsx
  src/components/mypage/component/ProfileCard.tsx
  src/components/mypage/component/ScoreEditModal.tsx
  src/components/mypage/component/ScoreHeader.tsx
  src/pages/mypage/index.tsx
  src/types/request.d.ts
  src/utils/constant/index.ts
  src/utils/index.ts
  src/utils/state.ts
  yarn.lock
Labels: young

#35 [FEAT] 모바일 nav 이름 정보 api 추가
  src/components/common/header/NavProfileCard.tsx
Labels: gildong

#39 [REFACTOR] 쿠키와 리코일을 통한 로그인 유지, 토큰, 유저 상태 관리, 출결사항 수정 시 refetch
  src/apis/account.ts
  src/apis/mypage.ts
  src/components/common/header/MobileNavModal.tsx
  src/components/common/header/NavBar.tsx
  src/components/common/header/NavProfileCard.tsx
  src/components/mypage/MyScoreSection.tsx
  src/components/mypage/TotalScoreSection.tsx
  src/components/mypage/component/ProfileCard.tsx
  src/components/mypage/component/ScoreEditModal.tsx
  src/components/mypage/component/UserEditModal.tsx
  src/components/signup/SignUpFormSection.tsx
  src/pages/google.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/types/request.d.ts
  src/utils/state.ts
Labels: young

#40 Attendance api 연결
  src/apis/attendance.ts
  src/components/attendance/completed/component/EntireTrackAttendance.tsx
  src/components/attendance/completed/component/TrackAttendance.tsx
  src/components/attendance/incompleted/InCompletedSection.tsx
  src/components/attendance/incompleted/component/AttendanceBox.tsx
  src/types/request.d.ts
Labels: gildong

#42 출석부 생성 기능
  src/apis/mypage.ts
  src/components/mypage/component/MakeAttendacneModal.tsx
  src/components/mypage/component/MakeAttendanceButton.tsx
  src/pages/mypage/index.tsx
Labels: gildong

#44 Archiving/detail
  src/components/archiving/Archiving.tsx
  src/components/archiving/Card.tsx
  src/components/archiving/Carousel.tsx
  src/components/project/detail/component/teamIntroduction/LinkButton.tsx
  src/pages/gallery/[gallery_id].tsx
  src/pages/project/[project_id].tsx
  src/pages/session/[session_id].tsx
  src/types/request.d.ts
  src/utils/index.ts
Labels: gildong
